version: "2.4"

services:
  db:
    image: postgres:17 # Use a specific PostgreSQL version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_bot # Or your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage
      - active_storage_data:/app/storage
    ports:
      - "5432:5432" # Expose PostgreSQL port to host

  web:
    build: . # Build the image from the current directory (where Dockerfile is)
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "80:3000" # Expose Rails port to host
    depends_on:
      - db # Ensure database starts before Rails
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/book_bot # Connect to the 'db' service

  solid_queue_worker:
    build: . # Or a specific image if you have a separate worker image
    command: bundle exec rake solid_queue:start # Or a custom script that starts the Solid Queue worker
    depends_on:
      - db # Solid Queue relies on the database
    environment:
      RAILS_ENV: production # Or production, depending on your setup
      DATABASE_URL: postgres://postgres:password@db:5432/book_bot # Connect to the 'db' service
volumes:
  postgres_data: # Define the named volume for PostgreSQL data
  active_storage_data: